# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

link_with 'CrowdShelf'

target 'CrowdShelf' do
    pod 'MTBBarcodeScanner', '~> 1.6.1'
    pod 'Alamofire', '~> 2.0'
    pod 'Mixpanel'
    pod 'CryptoSwift', '~> 0.1.1'
end

target 'CrowdShelfTests' do
    pod 'MTBBarcodeScanner', '~> 1.6.1'
    pod 'Alamofire', '~> 2.0'
    pod 'Mixpanel'
end	

