# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'
use_frameworks!

target 'CrowdShelf' do
	pod 'MTBBarcodeScanner', '~> 1.6.1'
	pod 'SwiftyJSON', '~> 2.2.1'
end

target 'CrowdShelfTests' do
	pod 'MTBBarcodeScanner', '~> 1.6.1'
	pod 'SwiftyJSON', '~> 2.2.1'
end	

